version: '3'
services:
  database:
    image: postgres:latest
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data2/
    ports:
      - "5432:5432"

volumes:
  database-data: